### ISSUE TITLE
fix main // errors while running >> java -jar jRT.jar <<

### ISSUE THREAD

**Issue by fijiol** [fijiol/ioHiccup#9]
> > Of course, it is written that jRT is an agent, and there is a readme.. but wouldn’t it be better to have more user-friendly output than we have in case when we try to just run it?

$ java -jar jRT.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AgentInitializationException
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
at java.lang.Class.getMethod0(Class.java:3018)
at java.lang.Class.getMethod(Class.java:1784)
at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AgentInitializationException
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 7 more

**Comment by eostermueller** [comment]
To get jRT to attach to a running JVM, I had to do two things:
1) include the following: -Xbootclasspath/a:tools.jar:jRT.jar   ....and of course both jar files had to have absolute path locations.
2) ...and pull request #10

--Erik
